title: FraponicMid
author: LWFlouisa
email: yjsybhvfn@tznvy.pbz
description: > # this means to ignore newlines until "show_exerpts:"
  This is the creole stage between Os Azusacos and Early Fraponic.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: LWFlouisa
    # github:  LWFlouisa
    # tumblr: https://redserpentpolitics.tumblr.com/
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: sarahrweaver
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: 
    # youtube_channel: UC0STgldrphgGmXK6N-pdSkA
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jemoji
